# Generated by Django 4.1.7 on 2023-03-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_age_alter_lead_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
