# Generated by Django 4.1.7 on 2023-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_category_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='icon',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
