# Generated by Django 4.1.7 on 2023-03-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_remove_lead_age_lead_email_alter_lead_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='area_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.areacode'),
        ),
    ]
