# Generated by Django 4.1.7 on 2023-03-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_areacode_lead_phone_lead_area_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacode',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
