# Generated by Django 4.1.7 on 2023-03-12 23:05

from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_areacode_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacode',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=leads.models.get_followup_folder_name)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
