# Generated by Django 4.1.7 on 2023-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_followup_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='file',
            new_name='my_file',
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
