# Generated by Django 4.1.7 on 2023-03-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_rename_file_followup_my_file_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
