# Generated by Django 4.1.7 on 2023-03-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_alter_followup_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
