# Generated by Django 4.1.7 on 2023-03-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_lead_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
